const types = {
  //user
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED:',
  REGISTER: 'REGISTER',
  LOGIN_WITH_GOOGLE: 'LOGIN_WITH_GOOGLE',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  RESET_PASSWORD: 'RESET_PASSWORD',

  SET_AUTH_PERSISTENCE: 'SET_AUTH_PERSISTENCE',
  ON_AUTHSTATE_SUCCESS: 'ON_AUTHSTATE_SUCCESS',
  ON_AUTHSTATE_FAILED: 'ON_AUTHSTATE_FAILED',

  //Product
  GET_POPULAR_PRODUCTS: 'GET_POPULAR_PRODUCTS',
  GET_POPULAR_PRODUCTS_SUCCESS: 'GET_POPULAR_PRODUCTS_SUCCESS',
  GET_POPULAR_PRODUCTS_FAILED: 'GET_POPULAR_PRODUCTS_FAILED',

  GET_TOP_RATE_PRODUCTS: 'GET_TOP_RATE_PRODUCTS',
  GET_TOP_RATE_PRODUCTS_SUCCESS: 'GET_TOP_RATE_PRODUCTS_SUCCESS',
  GET_TOP_RATE_PRODUCTS_FAILED: 'GET_TOP_RATE_PRODUCTS_FAILED',

  GET_ARRIVAL_PRODUCTS: 'GET_ARRIVAL_PRODUCTS',
  GET_ARRIVAL_PRODUCTS_SUCCESS: 'GET_ARRIVAL_PRODUCTS_SUCCESS',
  GET_ARRIVAL_PRODUCTS_FAILED: 'GET_ARRIVAL_PRODUCTS_FAILED',

  GET_BANNER_TRENDING: 'GET_BANNER_TRENDING',
  GET_BANNER_TRENDING_SUCCESS: 'GET_BANNER_TRENDING_SUCCESS',
  GET_BANNER_TRENDING_FAILED: 'GET_BANNER_TRENDING_FAILED',

  GET_GENDER_PRODUCTS: 'GET_GENDER_PRODUCTS',
  GET_GENDER_PRODUCTS_SUCCESS: 'GET_GENDER_PRODUCTS_SUCCES',
  GET_GENDER_PRODUCTS_FAILED: 'GET_GENDER_PRODUCTS_FAILED',

  GET_PRODUCT_BY_CATEGORY: 'GET_PRODUCT_BY_CATEGORY',
  GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
  GET_PRODUCT_BY_CATEGORY_FAILED: 'GET_PRODUCT_BY_CATEGORY_FAILED',

  GET_PRODUCT_BY_BRAND: 'GET_PRODUCT_BY_BRAND',
  GET_PRODUCT_BY_BRAND_SUCCESS: 'GET_PRODUCT_BY_BRAND_SUCCESS',
  GET_PRODUCT_BY_BRAND_FAILED: 'GET_PRODUCT_BY_BRAND_FAILED',

  //Category
  GET_LIST_CATEGORIES: 'GET_LIST_CATEGORIES',
  GET_LIST_CATEGORIES_SUCCESS: 'GET_LIST_CATEGORIES_SUCCESS',
  GET_LIST_CATEGORIES_FAILED: 'GET_LIST_CATEGORIES_FAILED',

  //Brand
  GET_LIST_BRANDS: 'GET_LIST_BRANDS',
  GET_LIST_BRANDS_SUCCESS: 'GET_LIST_BRANDS_SUCCESS',
  GET_LIST_BRANDS_FAILED: 'GET_LIST_BRANDS_FAILED',

  //Cart
  CLEAR_CART: ' CLEAR_CART',
  ADD_TO_CART: ' ADD_TO_CART',
  MINUS_TO_CART: ' MINUS_TO_CART',
  DELETE_TO_CART: ' DELETE_TO_CART',

  //checkout
  SET_CHECKOUT_SHIPPING_DETAILS: 'SET_CHECKOUT_SHIPPING_DETAILS',
  SET_CHECKOUT_PAYMENT_DETAILS: 'SET_CHECKOUT_PAYMENT_DETAILS',
  RESET_CHECKOUT: 'RESET_CHECKOUT',

  //Filter

  RESET_FILTER: 'RESET_FILTER',
  APPLY_FILTER: 'APPLY_FILTER'
};
export default types;
